name:                hs-minghu6
version:             0.1.0.0
github:              "githubuser/hs-minghu6"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hs-minghu6#readme>

dependencies:
- base >= 4.7 && < 5
- QuickCheck

library:
  source-dirs: src

executables:
  hs-minghu6-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-minghu6

tests:
  hs-minghu6-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-minghu6
    - QuickCheck

  hs-minghu6-doctest:
    main:                doctest.hs
    source-dirs:         doctest
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-minghu6
    - doctest > 0.8